### ISSUE TITLE
Support for Model 321

### ISSUE THREAD

**Issue by SRudinsky** [lakeshorecryotronics/python-driver#1]
Is it possible to add support for the Model 321 temperature controller?

**Comment by Noah-Lake-Shore-Cryotronics** [comment]
Thanks for the request. Unfortunately, we aren't planning to extend the python driver to specifically handle any of our instruments that don't have USB or Ethernet connections. For our 300 Series instruments, the main value of this driver is to simplify the process of finding and connecting to the correct virtual COM port. Since the 321 requires an external USB to serial adapter, we wouldn't be able to connect automatically like we do with our supported instruments.

If you would like some help connecting and communicating with the 321 manually using python, the Lake Shore Cryotronics forum would be a good place to ask the question. Our support team actively monitors the forum for requests for assistance. https://forums.lakeshore.com/board/91/temperature-controllers-monitors
