### ISSUE TITLE
Multiple Model 336's?

### ISSUE THREAD

**Issue by janasikm** [lakeshorecryotronics/python-driver#5]
Hi! I'm wondering if there is a functionality to use multiple Lakeshore Model 336's at the same time? I have not tried using it yet but the way it's written looks like there may be some issues picking and choosing which one to use, but I could be wrong of course. Thanks!

**Comment by Noah-Lake-Shore-Cryotronics** [comment]
Absolutely! When creating an instrument instance you may use a variety of unique identifiers to connect to a specific instrument rather than the first one the driver finds. Take a look at [this section](https://lake-shore-python-driver.readthedocs.io/en/latest/getting_started.html#connecting-to-a-specific-instrument) of our documentation.

**Comment by janasikm** [comment]
Perfect! Thanks so much I must have missed this part of the documentation.

Molly Janasik
University of Arizona | Lunar and Planetary Lab

From: ***@***.***>
Sent: Thursday, August 11, 2022 9:47 AM
To: ***@***.***>
Cc: Janasik, Molly - ***@***.***>; ***@***.***>
Subject: [EXT]Re: [lakeshorecryotronics/python-driver] Multiple Model 336's? (Issue #5)


External Email

Absolutely! When creating an instrument instance you may use a variety of unique identifiers to connect to a specific instrument rather than the first one the driver finds. Take a look at this section<https://lake-shore-python-driver.readthedocs.io/en/latest/getting_started.html#connecting-to-a-specific-instrument> of our documentation.
